// <auto-generated />
using System;
using Hrincescu_Alexandru_Examen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hrincescu_Alexandru_Examen.Migrations
{
    [DbContext(typeof(Hrincescu_Alexandru_ExamenContext))]
    [Migration("20210112140611_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hrincescu_Alexandru_Examen.Models.JocuriVideo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataLansarii")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preţ")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titlu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("JocuriVideo");
                });
#pragma warning restore 612, 618
        }
    }
}
